# Generated by Django 5.1 on 2024-08-27 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_profile_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Availability',
            field=models.CharField(choices=[('pre_order', 'pre_order'), ('In stock', 'In stock'), ('Out of Stock', 'out of stock')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.brand'),
        ),
    ]
