# Generated by Django 5.1 on 2024-09-03 05:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_image1_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('ispay', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 9, 2, 23, 11, 8, 676668))),
                ('image', models.ImageField(upload_to='order/image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
